spring:
  datasource:
    url: jdbc:h2:tcp:localhost/~/h2/db/hci-darkmode
    username: sa
    password: darkmode
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect

logging.level:
  org.hibernate:
    SQL: debug
    type: trace